-- MySQL Script generated by MySQL Workbench
-- Thu Jan 23 15:05:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Portfolio_M152
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Portfolio_M152` ;

-- -----------------------------------------------------
-- Schema Portfolio_M152
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Portfolio_M152` DEFAULT CHARACTER SET utf8 ;
USE `Portfolio_M152` ;

-- -----------------------------------------------------
-- Table `Portfolio_M152`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Portfolio_M152`.`post` ;

CREATE TABLE IF NOT EXISTS `Portfolio_M152`.`post` (
  `idPost` INT NOT NULL AUTO_INCREMENT,
  `commentaire` VARCHAR(45) NOT NULL,
  `creationDate` DATETIME NOT NULL,
  `modificationDate` DATETIME NULL,
  PRIMARY KEY (`idPost`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Portfolio_M152`.`media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Portfolio_M152`.`media` ;

CREATE TABLE IF NOT EXISTS `Portfolio_M152`.`media` (
  `idMedia` INT NOT NULL AUTO_INCREMENT,
  `nomMedia` VARCHAR(45) NOT NULL,
  `typeMedia` VARCHAR(45) NOT NULL,
  `creationDate` DATETIME NOT NULL,
  `modificationDate` DATETIME NULL,
  PRIMARY KEY (`idMedia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Portfolio_M152`.`contenir`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Portfolio_M152`.`contenir` ;

CREATE TABLE IF NOT EXISTS `Portfolio_M152`.`contenir` (
  `post_idPost` INT NOT NULL,
  `media_idMedia` INT NOT NULL,
  INDEX `fk_contenir_post_idx` (`post_idPost` ASC) VISIBLE,
  INDEX `fk_contenir_media1_idx` (`media_idMedia` ASC) VISIBLE,
  CONSTRAINT `fk_contenir_post`
    FOREIGN KEY (`post_idPost`)
    REFERENCES `Portfolio_M152`.`post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contenir_media1`
    FOREIGN KEY (`media_idMedia`)
    REFERENCES `Portfolio_M152`.`media` (`idMedia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
